version: '2'
services:
  eosio:
    image: eosio/eos:dawn3x
    command: /opt/eosio/bin/nodeosd.sh --resync-blockchain
    volumes:
    - ./eosio-volume/config:/opt/eosio/bin/data-dir
    - ./eosio-volume/data:/opt/eosio/var
  db:
    #build: ./database/
    image: postgres:latest
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
        POSTGRES_PASSWORD: password
        POSTGRES_USER: postgres
        POSTGRES_DB: block_one
  web:
    build: .
    ports:
    - "3000:3000"
    - "4000:4000"
    volumes:
    - .:/usr/src/app
    depends_on:
      - db
      - eosio
    links:
      - db
      - eosio
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; npm start'
    environment:
      DATABASE_HOST: db
      EOS_HOST: eosio